name: Docker

on:
  push:
    branches: 
      main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo docker build -t hello_world .
          sudo docker run hello_world
